### ISSUE TITLE
Error in installing in raspbian 

### ISSUE THREAD

**Issue by abhibhatia98** [sebi2k1/node-can#94]
Hi @sebi2k1  I am trying to install the library but it fails with error, log file is attached for your reference. 

[log.txt](https://github.com/sebi2k1/node-can/files/6122535/log.txt)

I will be thankful if you can help me.

Thanks
Abhishek

**Comment by sebi2k1** [comment]
No idea, sorry. Looks like some issue with the node-dev headers in this environment. nodejs v12 is already supported and th CI builds on Xenial.

@juleq Ever seen this?

**Comment by juleq** [comment]
Hi there,

I have never used node red, I always just install the socketcan package.

I have just checked into a pi, updated everything and npm installed socketcan. That resolved to socketcan@2.9.1 and it built just fine.

I remembered having seen an old version of the package under the name node-can. Npm installing that resolves to node-can@0.0.3-alpha.2. This does fail in a similar fashion as @abhibhatia98 attempt.

The log @abhibhatia98 has provided tries installing socketcan@2.1.3, which is fairly old.

@abhibhatia98 maybe asking the maintainer of the node-red-contrib-canbus package to update his socketcan dependency from 2.1.3 to 2.9.1 is the best way to fix your issue. I am not familiar with node red, but since the socketcan module API has been rather stable, maybe you can also update to the latest version yourself.

@sebi2k1 I vaguely remember that there has been a change to the v8 or nan API a while back that you have fixed back then. I guess it was somewhere between 2.1.3 and 2.9.1?

**Comment by grodansparadis** [comment]
@abhibhatia98  You can try if [node-red-contrib-socketcan ](https://flows.nodered.org/node/node-red-contrib-socketcan) works better for you.

**Comment by sebi2k1** [comment]
@juleq You are right, node-red-contrib-canbus (used by @abhibhatia98) includes socketcan-2.1.x only, which is too old for v12. Which was fixed by @tuna-f1sh after v.2.4.0.

Issue closed.
